version: '3'

services:
  mysql:
    image: mysql:5.7
    networks:
      - datatest-net
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=datatest
      - MYSQL_USER=datatest-user
      - MYSQL_PASSWORD=datatest-pass
  php:
    build: ./php
    networks:
      - datatest-net
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
  phpmyadmin:
    networks:
      - datatest-net
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'mysql'
    ports:
      - '127.0.0.1:8085:80'
networks:
  datatest-net:
